- id: 100
  key: renminbi
  currency: cny
  sort_order: 2
  bank_accounts:
    -
      bank: 'CMB'
      branch: 'CMB BEIJING'
      holder: 'PAOLU EX'
      account: '1'
- id: 200
  key: dollar
  currency: usd
  sort_order: 4
  bank_accounts:
    -
      bank: 'CMB'
      branch: 'CMB BEIJING'
      holder: 'PAOLU EX'
      account: '3'
- id: 300
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: ethereum
  currency: eth
  sort_order: 3
  min_confirm: 1
  max_confirm: 3